apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-files-claim
      containers:
        - name: ping-pong
          image: jayzstep/ping-pong:v0.6
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
          env:
            - name: PORT
              value: '3000'
