apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-pv
spec:
  storageClassName: shared-pv # t채ll채 nimell채 vaaditaan volyymia
  capacity:
    storage: 2Gi
  volumeMode: Filesystem # n채kyy hakemistona podeille
  accessModes:
    - ReadWriteOnce
  local:
    path: /tmp/kube
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3d-k3s-default-agent-0
