apiVersion: apps/v1
kind: Deployment
metadata:
  name: dwk-project-dep
spec:
  selector:
    matchLabels:
      app: dwk-project
  replicas: 1
  template:
    metadata:
      labels:
        app: dwk-project
    spec:
      volumes:
        - name: project-files
          persistentVolumeClaim:
            claimName: shared-files-claim
      containers:
        - name: dwk-project
          image: jayzstep/dwk-project:v0.9
          env:
            - name: PORT
              value: '3000'
          volumeMounts:
            - name: project-files
              mountPath: /usr/src/app/files
