apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: dwk-project-dep
spec:
  selector:
    matchLabels:
      app: dwk-project
  replicas: 1
  template:
    metadata:
      labels:
        app: dwk-project
    spec:
      volumes:
        - name: project-files
          persistentVolumeClaim:
            claimName: shared-files-claim
      containers:
        - name: dwk-project
          image: jayzstep/dwk-project:v0.12
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: port
            - name: PIC_URL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: pic_url
            - name: UPDATE_INTERVAL
              valueFrom:
                configMapKeyRef:
                  name: project-config
                  key: update_interval
          volumeMounts:
            - name: project-files
              mountPath: /usr/src/app/files
