apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: project
  name: shared-files-claim
spec:
  storageClassName: shared-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
