apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-duo
  template:
    metadata:
      labels:
        app: log-output-duo
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: shared-files-claim
      containers:
        - name: log-output
          image: jayzstep/log-output:v0.7
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
