apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: exercises
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output-duo
  template:
    metadata:
      labels:
        app: log-output-duo
    spec:
      volumes:
        - name: shared-logs
          persistentVolumeClaim:
            claimName: exercises-shared-files-claim
        - name: configmap-volume
          configMap:
            name: log-output-configmap
      containers:
        - name: log-output
          image: jayzstep/log-output:v0.9
          volumeMounts:
            - name: shared-logs
              mountPath: /usr/src/app/files
            - name: configmap-volume
              mountPath: /usr/src/app/config
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-configmap
                  key: message
