apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: exercises
  name: exercises-shared-files-claim
spec:
  storageClassName: exercises-shared-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
